mojohaus/flatten-maven-plugin

pom.xml
src/main/java/org/codehaus/mojo/flatten/FlattenDescriptor.java
src/main/java/org/codehaus/mojo/flatten/PomProperty.java

I added the support of the pluginManagement section as described in issue #9

support pluginManagement

---

src/it/projects/system-scope-dep-variable/pom.xml
src/it/projects/system-scope-dep-variable/src/main/java/test/FlattenPluginTest.java

Adding IT for #12   Please uncomment the build section of the POM to see the issue.

Adding IT for Issue #12

---

src/it/projects/fat-jar/pom.xml
src/it/projects/fat-jar/verify.groovy
src/main/java/org/codehaus/mojo/flatten/FlattenMode.java

Add flatten mode fat-jar (removes all dependencies)

---

pom.xml
src/it/projects/parent-with-version-range/pom.xml
src/it/projects/parent-with-version-range/verify.groovy
src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
src/main/java/org/codehaus/mojo/flatten/model/resolution/FlattenModelResolver.java
src/test/java/org/codehaus/mojo/flatten/CreateEffectivePomTest.java

As requested per  #36.
This pull request is based on pull request #34. 
- Commit c548731 adds an integration test for version ranges in parents.
- Commit 8eb15d2 is a non-working attempt to implement version ranges for parents.

Resolve parent with version range

---

src/it/projects/os-profile-active-in-parent/parent/pom.xml
src/it/projects/os-profile-active-in-parent/pom.xml
src/it/projects/os-profile-active-in-parent/verify.groovy
src/it/projects/os-profile-active/pom.xml
src/it/projects/os-profile-inactive/pom.xml
src/it/projects/profile-with-dependencies-active/pom.xml
src/it/projects/profile-with-dependencies-not-triggered/pom.xml
src/it/projects/profile-with-dependencies-triggered-by-folder-presence/parent/pom.xml
src/it/projects/profile-with-dependencies-triggered-by-folder-presence/pom.xml
src/it/projects/profile-with-dependencies-triggered-by-folder-presence/verify.groovy
src/it/projects/profile-with-dependencies-triggered/pom.xml
src/it/projects/property-profile-active/pom.xml
src/it/projects/property-profile-inactive/pom.xml

Additional ITs to reproduce issue #14.

additional its for #14

---

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java

The missing Javadoc update for #77.

Add resolveCiFriendliesOnly to the flattenMode Javadoc table

---

.travis.yml

https://github.com/mojohaus/flatten-maven-plugin/pull/98#issuecomment-493861281
Solution as advised here: https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/9

Fix oraclejdk8 problem on Travis

---

.mvn/wrapper/maven-wrapper.properties
.travis.yml
pom.xml
src/it/projects/no-overwrite/.flattened-pom.xml
src/it/projects/no-overwrite/verify.groovy
src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java

bump parent pom so we can now use 1.7
Signed-off-by: olivier lamy <olamy@apache.org>

fix #136 use https in pom file as it is now done in maven 3.6.3 and so update travis etc bump parent pom so we can now use 1.7

---

src/it/projects/profile-with-dependencies-inherit-parent-dependencyManagement/parent/pom.xml
src/it/projects/profile-with-dependencies-inherit-parent-dependencyManagement/pom.xml
src/it/projects/profile-with-dependencies-inherit-parent-dependencyManagement/verify.groovy
src/main/java/org/codehaus/mojo/flatten/Dependencies.java
src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java

Fix embedBuildProfileDependencies bug

---

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
src/main/java/org/codehaus/mojo/flatten/ModelBuilderThreadSafetyWorkaround.java
src/test/java/org/codehaus/mojo/flatten/CreateEffectivePomTest.java

Fixes #143 
@lasselindqvist & @olamy I consider this an important fix which justifies a timely release. Build stability is key! Thanks for your attention.
@McFoggy & @wheene since you were the ones originally requesting the support for jgitver via #87 (that led to this problem): Can you please check whether jgitver still works with this PR? Thanks!

Fix #143: Switch back to custom DefaultModelBuilder to fix parallel builds

---

src/test/java/org/codehaus/mojo/flatten/FlattenMojoTest.java

Fix FlattenMojoTest on Windows

---

CONTRIBUTING.md

Remove outdated CONTRIBUTING.md file

---

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java

Hi
little optimization: use replace and not replaceall if there is not a regular expression.
ciao
matteo

Use replace for non regular expression replace

---

src/main/java/org/codehaus/mojo/flatten/Dependencies.java
src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
src/main/java/org/codehaus/mojo/flatten/KeepCommentsInPom.java
src/main/java/org/codehaus/mojo/flatten/PomProperty.java
src/main/java/org/codehaus/mojo/flatten/cifriendly/CiModelInterpolator.java
src/main/java/org/codehaus/mojo/flatten/model/resolution/ReactorModelPool.java

Signed-off-by: Olivier Lamy <olamy@apache.org>

fix some ide warmings and modernize a bit

---

src/it/projects/profile-with-depMgmt-transitive/pom.xml
src/it/projects/profile-with-depMgmt-transitive/verify.groovy
src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java

This PR provides a test to reproduce #320 and a possible (although possibly naive) fix.

#320 Fix importing dependency management in profiles from BOM imports

---

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java

goal flatten: fix: for parameter FlattenDependencyMode=all the text "-SNAPSHOT" in the version of dependencies is replaced by timestamp sometime. After fix the text "-SNAPSHOT" will be kept

goal flatten: parameter FlattenDependencyMode=all replaces "-SNAPSHOT"

---

src/it/projects/flatten-shaded-drp/pom.xml

Bump m-shade-p to 3.4.1 in flatten-shaded-drp test - fix for Maven 4

---

pom.xml

https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/codehaus/mojo/flatten-maven-plugin/README.md

upgrade sisu.inject: fixes Reproducible Builds

---

src/main/java/org/codehaus/mojo/flatten/extendedinterpolation/FilteringValueSourceWrapper.java
src/test/java/org/codehaus/mojo/flatten/extendedinterpolation/ExtendedStringSearchModelInterpolatorTest.java

Fix FilteringValueSourceWrapper for a newer version of plexus-interpolation, Maven 3.9.10

---

pom.xml

Fix typo in License name

---

src/main/java/org/codehaus/mojo/flatten/CleanMojo.java

Remove a dead link to MOJO-2030 from documentation

---

src/it/projects/resolve-properties-ci-do-not-interpolate-profile-activation-file/pom.xml
src/it/projects/resolve-properties-ci-do-not-interpolate-profile-activation-file/verify.groovy
src/main/java/org/codehaus/mojo/flatten/AbstractFlattenMojo.java
src/main/java/org/codehaus/mojo/flatten/CleanMojo.java
src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
src/test/java/org/codehaus/mojo/flatten/KeepCommentsInPomTest.java

Create missing target directories, use NIO for file block operations

---

src/it/projects/flatten-deploy/invoker.properties
src/it/projects/flatten-deploy/pom.xml
src/it/projects/flatten-deploy/verify.groovy

Add integration test for install and deploy flattened pom
