mojohaus/flatten-maven-plugin

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
FlattenMojo.profileInjector and FlattenMojo.profileSelector are then also used outside of Flatten-Mojos.
That prevents the property 'tools.jar' to be set accordingly during Maven initialize lifecycle, because the profile 'default-tools.jar' in com.sun.xml.ws:project:2.2.10 gets not activated.
The resulting error is as following:
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/xjc/api/ErrorListener
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
...
=> FlattenMojo must not change DefaultModelBuilder as it is created once per session

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
The document does not specify that the `updatePomFile` property default value is set to `true` if the `flattenMode` is set to `bon`.
=> Add precision about updatePomFile property in documentation

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
Adds a sentence that explains what happens to plugin declarations which
load extensions.
=> Resolve #28: Improve Javadoc for flatten goal

pom.xml, src/it/mrm/repository/parent-depMngt-properties.pom, src/it/projects/complete-multimodule-parent-pom-cifriendly/invoker.properties, src/it/projects/complete-multimodule-parent-pom-cifriendly/module-with-parent/pom.xml, src/it/projects/complete-multimodule-parent-pom-cifriendly/module/pom.xml, src/it/projects/complete-multimodule-parent-pom-cifriendly/pom.xml, src/it/projects/complete-multimodule-parent-pom-cifriendly/verify.groovy, src/it/projects/inherit-parent-dependencyManagement-cifriendly/invoker.properties, src/it/projects/inherit-parent-dependencyManagement-cifriendly/pom.xml, src/it/projects/inherit-parent-dependencyManagement-cifriendly/verify.groovy, src/it/projects/resolve-properties-ci/invoker.properties, src/it/projects/resolve-properties-ci/pom.xml, src/it/projects/resolve-properties-ci/verify.groovy, src/main/java/org/codehaus/mojo/flatten/FlattenMode.java, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolator.java, src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolatorImpl.java, src/main/java/org/codehaus/mojo/flatten/cifriendly/CiModelInterpolator.java, src/main/resources/META-INF/plexus/components.xml, src/test/java/org/codehaus/mojo/flatten/CreateEffectivePomTest.java
Here is one possible implementation of CI friendly variable resolver.
This has some things I don't personally like. For example CiInterpolatorImpl just basically replicates StringSearchInterpolator because first I tried to extend it and overwrite just some of the methods but that lead to weird classloading issues that I didn't have the energy to solve.
Also resolving variables inside profile dependencies doesn't work as it should but that is because of the multiple other problems in profile resolving in the flatten plugin.
Now I have found out that there might be some better solutions to flattening CI variables in poms. Like https://github.com/fmarot/cifriendly-maven-plugin which seems to be a much simpler approach to solving just this one problem. I haven't tried that plugin though. …
=> Ci friendly

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/test/java/org/codehaus/mojo/flatten/CreateEffectivePomTest.java
When working with [jgitver](https://github.com/jgitver/jgitver-maven-plugin) I hit a problem where processed versions produced by the extension were not getting picked up during flatten execution. I tracked this bug (?) down to `FlattenMojo` where `ModelBuilder` instance is obtained using `new`, thus the custom impl of this interface provided by jgitver is not picked up and versions are not processed. 
This PR proposes to inject `ModelBuilder` into the MOJO so custom implementations provided by extensions in general (and jgitver in our particular case) have a chance to get picked up.
I do not have a reproducer case at the moment, but the proposed change fixes the problem for us and does not seem to break any existing behavior.
cc @McFoggy
=> Use injection in FlattenMojo to work with jgitver

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolatorImpl.java
The TODO annotation prevents docs pushing, the others only create warnings.
This is needed before the site can be published.
=> Fix Javadocs

src/it/projects/no-overwrite-3.6.2-before/verify.groovy, src/it/projects/no-overwrite-3.6.3-later/verify.groovy, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
@olamy , @stephaniewang526 
- fix the problem when parsing version by using "./mvnw -v".
- fix the problem that we need to use "mvnw.cmd -v" to parse Maven version in Windows
- fix the problem of checking existing flattened pom resulting from the different line separator in Windows ("\r\n" instead of "\n")
=> Fixes no-overwrite test failure

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
This pull request fixes a a malformed tag in the Javadoc of a parameter of the `flatten` goal, which results in the tag showing up in the site.
=> Fix minor tag problem in flatten goal description

pom.xml, src/it/projects/resolve-properties-ci-do-not-interpolate-profile-activation-file/invoker.properties, src/it/projects/resolve-properties-ci-do-not-interpolate-profile-activation-file/pom.xml, src/it/projects/resolve-properties-ci-do-not-interpolate-profile-activation-file/verify.groovy, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/test/java/org/codehaus/mojo/flatten/FlattenMojoTest.java, src/test/resources/resolve-properties-ci-do-not-interpolate-profile-activation-file/pom.xml
Fixes #57 
Relates #114 
Relates [MNG-6802](https://issues.apache.org/jira/browse/MNG-6802), [MNG-5612](https://issues.apache.org/jira/browse/MNG-5612)
A profile activation file is being interpolated during `flatten-maven-plugin` run.
Example
```xml
<profile>
<id>dockerfile-update</id>
<activation>
<file>
<exists>Dockerfile</exists> 
</file>
</activation>
</profile>
```
Result
```xml
<profile>
<id>dockerfile-update</id>
<activation>
<file>
<exists>aboslute/path/resolved/on/building/machine/Dockerfile</exists>
</file>
</activation>
</profile>
```
The root of the problem in [FileProfileActivator.isActive()](https://github.com/apache/maven/blob/master/maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/FileProfileActivator.java#L70)
method.
It is called in …
=> #57 Prevent interpolation of a profile activation file

src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Eclipse m2e allows to provide lifecycle mapping metadata as part of the plugin itself. If present, such mapping metadata will be automatically used by m2e, thus eliminating the need for plugin specific project configurator and/or lifecycle mapping metadata in pom.xml.
Fixes #146
=> fix: Add lifecycle mapping metadata for M2E (Eclipse)

.github/workflows/maven.yml, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
=> use shared gh action asf

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/test/java/org/codehaus/mojo/flatten/FlattenMojoOmitExclusionsTest.java, src/test/resources/omit-exclusions/pom.xml
PR for https://github.com/mojohaus/flatten-maven-plugin/issues/288
=> #288 Add configuration option to omit dependency exclusions stanzas from flattened POM

src/site/xdoc/index.xml
I found the https://www.mojohaus.org/flatten-maven-plugin/#usage sections are mostly not working. This pull request updates them.
If this looks ok, please feel free to merge this.
=> fix broken links in index.html

src/main/java/org/codehaus/mojo/flatten/Dependencies.java, src/main/java/org/codehaus/mojo/flatten/FlattenDescriptor.java, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolatorImpl.java, src/main/java/org/codehaus/mojo/flatten/cifriendly/CiModelInterpolator.java, src/main/java/org/codehaus/mojo/flatten/model/resolution/ReactorModelPool.java
Hi
I have cleaned up the use of the diamond <> operator removing some extra code
ciao
matteo
=> Cleanup diamond <> operator

src/it/projects/profile-with-deps-inherit-parent-depMgmt-test/parent/pom.xml, src/it/projects/profile-with-deps-inherit-parent-depMgmt-test/pom.xml
Use unique artifactId and remove javax.annotations.version. Both
were copied from profile-with-deps-inherit-parent-depMgmt-jdk when the
profile-with-deps-inherit-parent-depMgmt-test was created and
it was apparently forgotten to adjust them.
=> Fix copypaste errors in ITs projects

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/main/java/org/codehaus/mojo/flatten/KeepCommentsInPom.java, src/test/java/org/codehaus/mojo/flatten/KeepCommentsInPomTest.java, src/test/resources/keep-comments-in-pom/expected-flattened-pom-jdk11.xml, src/test/resources/keep-comments-in-pom/expected-flattened-pom.xml, src/test/resources/keep-comments-in-pom/pom.xml
See https://github.com/mojohaus/flatten-maven-plugin/issues/269
=> Keep comments in .flattened-pom.xml

src/it/projects/flatten-shaded-drp/invoker.properties, src/it/projects/flatten-shaded-drp/pom.xml, src/it/projects/flatten-shaded-drp/src/main/java/com/example/Main.java, src/it/projects/flatten-shaded-drp/verify.groovy, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
Based on the discussion in https://github.com/apache/maven-shade-plugin/pull/129#discussion_r843695691 It seems that the flatten plugin should update the `originalModel` property after we flatten the pom.
This issue resolves #100 and is an alternate way to close #279
=> Set `project.originalModel` after flattening

src/it/projects/flatten-dependency-all-both-test-and-transitive/pom.xml, src/it/projects/flatten-dependency-all-both-test-and-transitive/verify.groovy, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
Fixes #185 , in which test-scope dependencies are unexpectedly excluded when 
- a library itself only uses the dependency as test
- but another dependency actually uses the dependency (non-test)
(The issue has a diagram to illustrate the mechanism)
The root cause is that, when building the dependency tree of the project, test-scope dependencies hides the actually-used dependencies with "omitted for duplicate" mark.
With this pull request, when building a dependency tree, the plugin removes the direct, test-scope dependencies. This avoids marking the actually-used dependencies as "omitted for duplicate".
This modification is safe because the test-scope dependencies are not visible to library users in any way.
=> Removing test-scope dependencies before building dependency tree

pom.xml, src/main/java/org/codehaus/mojo/flatten/CleanMojo.java, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/main/java/org/codehaus/mojo/flatten/KeepCommentsInPom.java, src/main/java/org/codehaus/mojo/flatten/ModelBuilderThreadSafetyWorkaround.java, src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolatorImpl.java, src/main/java/org/codehaus/mojo/flatten/cifriendly/CiModelInterpolator.java, src/main/java/org/codehaus/mojo/flatten/model/resolution/FlattenModelResolver.java, src/main/java/org/codehaus/mojo/flatten/model/resolution/ReactorModelPool.java, src/test/java/org/codehaus/mojo/flatten/CreateEffectivePomTest.java, src/test/java/org/codehaus/mojo/flatten/FlattenMojoOmitExclusionsTest.java, src/test/java/org/codehaus/mojo/flatten/FlattenMojoTest.java, src/test/java/org/codehaus/mojo/flatten/KeepCommentsInPomTest.java
- enable checkstyle plugin
- reformat code to meet checkstyle requirements
- reorder imports
=> Enable checkstyle verification during build

pom.xml, src/test/java/org/codehaus/mojo/flatten/KeepCommentsInPomTest.java
=> Bump commons-io to 2.11.0

pom.xml, src/it/projects/complete-multimodule-parent-pom-direct-dependencies/module-with-parent/pom.xml, src/it/projects/complete-multimodule-parent-pom-direct-dependencies/module/pom.xml, src/it/projects/complete-multimodule-parent-pom-direct-dependencies/pom.xml, src/it/projects/complete-multimodule-parent-pom-direct-dependencies/verify.groovy, src/it/projects/inherit-parent-dependency/pom.xml, src/it/projects/parent-with-version-range/pom.xml, src/main/java/org/codehaus/mojo/flatten/DirectDependenciesInheritanceAssembler.java, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/main/java/org/codehaus/mojo/flatten/ModelBuilderThreadSafetyWorkaround.java, src/main/resources/META-INF/sisu/javax.inject.Named
Hi @slawekjaranowski,
I created a new branch for issue #220 starting on top master and cherry-picked and adjusted.
Maybe this branch is better for a pull request.
I did not want to force push the bugfix/220 branch.
Best Regards,
Kemal
=> Fix #220 - multimodule-module-with-parent there is a missing direct-dependency

src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/test/java/org/codehaus/mojo/flatten/KeepCommentsInPomTest.java
The current version of the `flatten-maven-plugin` switches between LF and CRLF line endings based on the system name.
Reproducible builds require normalization of line endings on all systems.  This PR allows to change the generated line endings by passing an appropriate `-Dline.separator=...` option to Maven and therefore allows to use LF line endings also on Windows machines (or CRLF line endings on UNIX machines).
=> Use `System.lineSeparator()` on all systems

pom.xml, src/it/projects/flatten-dependency-all-depmgnt-optional/invoker.properties, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java, src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolatorImpl.java, src/main/java/org/codehaus/mojo/flatten/cifriendly/CiModelInterpolator.java, src/main/java/org/codehaus/mojo/flatten/model/resolution/FlattenModelResolver.java, src/main/java/org/codehaus/mojo/flatten/model/resolution/ReactorModelPool.java, src/main/resources/META-INF/plexus/components.xml, src/test/java/org/apache/maven/shared/transfer/dependencies/resolve/internal/DefaultTestDependencyResolver.java, src/test/java/org/codehaus/mojo/flatten/CreateEffectivePomTest.java
As part of user reported issue https://issues.apache.org/jira/browse/MRESOLVER-322 and for upcoming 1.9.5 resolver release went to look what it is about, only to figure out that this plugin accumulate several terrible lag, bad practice and many other things.
Whenever you see "inappropriate dependency" (ie. using MAT in plugin that declares itself as a 3.2.5+ plugin), use of deprecated components (ArtifactFactory, ArtifactRepository as local repository and relatives), or doing hoops and loops to get dependnecy graph ONLY to do something about it, step up and fix it. Or call the Ghostbusters!
These changes makes plugin work as expected from declared "minimum" version (3.2.5) to current stable (3.9.0) with addition that it will support split repository and any other modern feature …
=> Remove old and deprecated items, use Resolver API

.github/workflows/maven.yml, pom.xml, src/it/projects/bom-flattenMode/pom.xml, src/it/projects/bom-pomElements/pom.xml, src/it/projects/complete-artifact-pom/pom.xml, src/it/projects/complete-artifact-pom/verify.groovy, src/it/projects/complete-mavenplugin-pom/pom.xml, src/it/projects/complete-mavenplugin-pom/verify.groovy, src/it/projects/complete-multimodule-parent-pom-cifriendly/pom.xml, src/it/projects/complete-multimodule-parent-pom-cifriendly/verify.groovy, src/it/projects/complete-multimodule-parent-pom-direct-dependencies/pom.xml, src/it/projects/complete-multimodule-parent-pom-direct-dependencies/verify.groovy, src/it/projects/complete-multimodule-parent-pom/pom.xml, src/it/projects/complete-multimodule-parent-pom/verify.groovy, src/it/projects/external-parent/pom.xml, src/it/projects/external-parent/verify.groovy, src/it/projects/issue-348-repository-from-project/pom.xml, src/it/projects/issue-348-repository-from-project/verify.groovy, src/it/projects/jdk-profile-inactive/pom.xml, src/it/projects/jdk-profile-inactive/verify.groovy, src/it/projects/optional-elements-modeMinimum/pom.xml, src/it/projects/optional-elements-modeMinimum/verify.groovy, src/it/projects/optional-elements-modeOss/pom.xml, src/it/projects/optional-elements-modeOss/verify.groovy, src/it/projects/optional-elements-modeOssrh/pom.xml, src/it/projects/optional-elements-modeOssrh/verify.groovy, src/it/projects/optional-elements-pomElements-legacy/pom.xml, src/it/projects/optional-elements-pomElements-legacy/verify.groovy, src/main/java/org/codehaus/mojo/flatten/model/resolution/FlattenModelResolver.java
- Update maven to 3.5.0
- Implement missing ModelResolver method
- Remove unsupported <reports/> tags
=> Update Maven to 3.5.0

src/main/java/org/codehaus/mojo/flatten/FlattenDescriptor.java, src/main/java/org/codehaus/mojo/flatten/FlattenMode.java
packaging, groupId and artifactId were not configurable.
=> Make more elements configurable in pomElements

pom.xml, src/it/projects/clean-skip/.flattened-pom.xml, src/it/projects/clean-skip/pom.xml, src/it/projects/clean-skip/verify.groovy, src/it/projects/flatten-skip/pom.xml, src/it/projects/flatten-skip/verify.groovy, src/it/projects/skip/.flattened-pom.xml, src/it/projects/skip/pom.xml, src/it/projects/skip/verify.groovy, src/main/java/org/codehaus/mojo/flatten/AbstractFlattenMojo.java, src/main/java/org/codehaus/mojo/flatten/CleanMojo.java, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
This introduces 3 flags:
- `flatten.skip`: skips the entire plugin regardless of goal
- `flatten.clean.skip`: skips the clean goal
- `flatten.flatten.skip`: skips the flatten goal
This means the user has control over what parts are skipped, and the flags are descriptive. The `flatten.` prefix is in line with other parameters like `flatten.mode` and `flatten.dependency.mode`.
Test cases have been added for all three flags. Of course, I also tested it locally. The resulting logs are as follows:
```
[INFO] --- flatten:1.5.1-SNAPSHOT:clean (flatten.clean) @ my-test-module ---
[INFO] Clean skipped.
```
```
[INFO] --- flatten:1.5.1-SNAPSHOT:flatten (flatten) @ my-test-module ---
[INFO] Flatten skipped.
```
Usage is either through passing parameters along with the command:
```sh
mvn <goal> …
```
=> Add skip flags

src/main/java/org/codehaus/mojo/flatten/FlattenDescriptor.java, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
Make it possible to replace the default operation ("flatten") with
another value. This is useful to e.g. strip a pom completely and then
only add a few elements back.
=> Make the default operation configurable

src/it/mrm/repository/parent-transitive-deps-1.pom, src/it/projects/complete-multimodule-parent-pom-direct-dependencies/pom.xml, src/it/projects/inherit-parent-dependency/pom.xml, src/it/projects/parent-with-version-range/pom.xml, src/main/java/org/codehaus/mojo/flatten/DirectDependenciesInheritanceAssembler.java, src/main/java/org/codehaus/mojo/flatten/FlattenDependencyMode.java, src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
... since 1.4.0. Introduce a new "inherited" flatten dependency mode that includes the inherited dependencies like "direct" did in 1.3.0. And make this the new default behaviour bringing it back to 1.3.0 and before
=> Fix Issue#377 Regression: parent dependencies missing in flattened pom
